# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ReactOKTA

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ba9e3a2b0f274a93aab5a7385936956f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ebe39ef5ad7b47a99ae88b5a39c9bca0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ba9e3a2b0f274a93aab5a7385936956f }}/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ReactOKTA'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_25129029c9d54e0a80afb32e082df222 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ba9e3a2b0f274a93aab5a7385936956f }}/staticsite:${{ github.sha }}'